version: '3.8'

services:
  shipyard:
    image: soulter/shipyard:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/bay.db
      - ACCESS_TOKEN=secret-token
      - MAX_SHIP_NUM=10
      - BEHAVIOR_AFTER_MAX_SHIP=wait
      - DOCKER_IMAGE=ship:latest
      - DOCKER_NETWORK=shipyard
    volumes:
      - bay_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - shipyard

volumes:
  bay_data:

networks:
  shipyard:
    external: true
